# hide_cursor_when_typing = true

[colors]
draw_bold_text_with_bright_colors = true
indexed_colors = []

[colors.bright]
black = "0x4d4d4d"
blue = "0xcaa9fa"
cyan = "0x9aedfe"
green = "0x5af78e"
magenta = "0xff92d0"
red = "0xff6e67"
white = "0xe6e6e6"
yellow = "0xf4f99d"

[colors.cursor]
cursor = "0xf8f8f2"
text = "0x44475a"

[colors.dim]
black = "0x14151b"
blue = "0x4d5b86"
cyan = "0x59dffc"
green = "0x1ef956"
magenta = "0xff46b0"
red = "0xff2222"
white = "0xe6e6d1"
yellow = "0xebf85b"

[colors.normal]
black = "0x000000"
blue = "0xbd93f9"
cyan = "0x8be9fd"
green = "0x50fa7b"
magenta = "0xff79c6"
red = "0xff5555"
white = "0xbfbfbf"
yellow = "0xf1fa8c"

[colors.primary]
background = "0x282a36"
foreground = "0xf8f8f2"

[env]
TERM = "xterm-256color"

[font]
size = 16

[font.bold]
family = "SauceCodePro Nerd Font"
style = "Bold"

[font.bold_italic]
family = "SauceCodePro Nerd Font"
style = "Bold Italic"

[font.italic]
family = "SauceCodePro Nerd Font"
style = "Italic"

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001Ba"
key = "A"
mods = "Option"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "B"
mods = "Option"

[[keyboard.bindings]]
chars = "\u001Bc"
key = "C"
mods = "Option"

[[keyboard.bindings]]
chars = "\u001Bd"
key = "D"
mods = "Option"

[[keyboard.bindings]]
chars = "\u001Be"
key = "E"
mods = "Option"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "F"
mods = "Option"

[[keyboard.bindings]]
chars = "\u001Bg"
key = "G"
mods = "Option"

[[keyboard.bindings]]
chars = "\u001Bh"
key = "H"
mods = "Option"

[[keyboard.bindings]]
chars = "\u001Bi"
key = "I"
mods = "Option"

[[keyboard.bindings]]
chars = "\u001Bj"
key = "J"
mods = "Option"

[[keyboard.bindings]]
chars = "\u001Bk"
key = "K"
mods = "Option"

[[keyboard.bindings]]
chars = "\u001Bl"
key = "L"
mods = "Option"

[[keyboard.bindings]]
chars = "\u001Bm"
key = "M"
mods = "Option"

[[keyboard.bindings]]
chars = "\u001Bn"
key = "N"
mods = "Option"

[[keyboard.bindings]]
chars = "\u001Bo"
key = "O"
mods = "Option"

[[keyboard.bindings]]
chars = "\u001Bp"
key = "P"
mods = "Option"

[[keyboard.bindings]]
chars = "\u001Bq"
key = "Q"
mods = "Option"

[[keyboard.bindings]]
chars = "\u001Br"
key = "R"
mods = "Option"

[[keyboard.bindings]]
chars = "\u001Bs"
key = "S"
mods = "Option"

[[keyboard.bindings]]
chars = "\u001Bt"
key = "T"
mods = "Option"

[[keyboard.bindings]]
chars = "\u001Bu"
key = "U"
mods = "Option"

[[keyboard.bindings]]
chars = "\u001Bv"
key = "V"
mods = "Option"

[[keyboard.bindings]]
chars = "\u001Bw"
key = "W"
mods = "Option"

[[keyboard.bindings]]
chars = "\u001Bx"
key = "X"
mods = "Option"

[[keyboard.bindings]]
chars = "\u001By"
key = "Y"
mods = "Option"

[[keyboard.bindings]]
chars = "\u001Bz"
key = "Z"
mods = "Option"

[[keyboard.bindings]]
chars = "\u001BA"
key = "A"
mods = "Option|Shift"

[[keyboard.bindings]]
chars = "\u001BB"
key = "B"
mods = "Option|Shift"

[[keyboard.bindings]]
chars = "\u001BC"
key = "C"
mods = "Option|Shift"

[[keyboard.bindings]]
chars = "\u001BD"
key = "D"
mods = "Option|Shift"

[[keyboard.bindings]]
chars = "\u001BE"
key = "E"
mods = "Option|Shift"

[[keyboard.bindings]]
chars = "\u001BF"
key = "F"
mods = "Option|Shift"

[[keyboard.bindings]]
chars = "\u001BG"
key = "G"
mods = "Option|Shift"

[[keyboard.bindings]]
chars = "\u001BH"
key = "H"
mods = "Option|Shift"

[[keyboard.bindings]]
chars = "\u001BI"
key = "I"
mods = "Option|Shift"

[[keyboard.bindings]]
chars = "\u001BJ"
key = "J"
mods = "Option|Shift"

[[keyboard.bindings]]
chars = "\u001BK"
key = "K"
mods = "Option|Shift"

[[keyboard.bindings]]
chars = "\u001BL"
key = "L"
mods = "Option|Shift"

[[keyboard.bindings]]
chars = "\u001BM"
key = "M"
mods = "Option|Shift"

[[keyboard.bindings]]
chars = "\u001BN"
key = "N"
mods = "Option|Shift"

[[keyboard.bindings]]
chars = "\u001BO"
key = "O"
mods = "Option|Shift"

[[keyboard.bindings]]
chars = "\u001BP"
key = "P"
mods = "Option|Shift"

[[keyboard.bindings]]
chars = "\u001BQ"
key = "Q"
mods = "Option|Shift"

[[keyboard.bindings]]
chars = "\u001BR"
key = "R"
mods = "Option|Shift"

[[keyboard.bindings]]
chars = "\u001BS"
key = "S"
mods = "Option|Shift"

[[keyboard.bindings]]
chars = "\u001BT"
key = "T"
mods = "Option|Shift"

[[keyboard.bindings]]
chars = "\u001BU"
key = "U"
mods = "Option|Shift"

[[keyboard.bindings]]
chars = "\u001BV"
key = "V"
mods = "Option|Shift"

[[keyboard.bindings]]
chars = "\u001BW"
key = "W"
mods = "Option|Shift"

[[keyboard.bindings]]
chars = "\u001BX"
key = "X"
mods = "Option|Shift"

[[keyboard.bindings]]
chars = "\u001BY"
key = "Y"
mods = "Option|Shift"

[[keyboard.bindings]]
chars = "\u001BZ"
key = "Z"
mods = "Option|Shift"

[[keyboard.bindings]]
chars = "\u001B1"
key = "Key1"
mods = "Option"

[[keyboard.bindings]]
chars = "\u001B2"
key = "Key2"
mods = "Option"

[[keyboard.bindings]]
chars = "\u001B3"
key = "Key3"
mods = "Option"

[[keyboard.bindings]]
chars = "\u001B4"
key = "Key4"
mods = "Option"

[[keyboard.bindings]]
chars = "\u001B5"
key = "Key5"
mods = "Option"

[[keyboard.bindings]]
chars = "\u001B6"
key = "Key6"
mods = "Option"

[[keyboard.bindings]]
chars = "\u001B7"
key = "Key7"
mods = "Option"

[[keyboard.bindings]]
chars = "\u001B8"
key = "Key8"
mods = "Option"

[[keyboard.bindings]]
chars = "\u001B9"
key = "Key9"
mods = "Option"

[[keyboard.bindings]]
chars = "\u001B0"
key = "Key0"
mods = "Option"

[[keyboard.bindings]]
chars = "\r"
key = "NumpadEnter"
mods = "None"

[window]
icon = "~/.config/alacritty/terminal.png"

[window.dimensions]
columns = 80
lines = 22
